name: generate filters
on:
  workflow_dispatch:
  push:

permissions:
  contents: write

jobs:
  update-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: npm i -g pnpm && pnpm i && node build.js
      - uses: stefanzweifel/git-auto-commit-action@v5
        with: 
          commit_message: Filter updated
          commit_author: github-actions[bot] <github-actions[bot]@users.noreply.github.com>